### ISSUE TITLE
I can't start DevToDev analytics with a second Unity project

### ISSUE THREAD

**Issue by sshumihin** [devtodev-analytics/unity-sdk#1]
Why do you write DTD settings (appID, Secret Key) to Editor Prefs?
It is a Global Settings for Unity, not for a project.
I have more than one project and DTD settings for a last opened project overwrite DTD settings for  another opened project.

Fix it please!

**Comment by sshumihin** [comment]
Unity 5.5.1, DTD 2.3.5
But I can't turn on Analytics. DTD plugin wants a first scene opened, but I have my first scene opened already.

**Comment by Skazochnij** [comment]
We obtain the names of the scenes from the Build Settings window, is your scene added there?
By the way the plugin writes the name of the scene in the error message. Is the name of your first scene written there?

<img width="641" alt="build settings 2017-02-28 15-43-04" src="https://cloud.githubusercontent.com/assets/3314943/23407466/b44406ee-fdcc-11e6-937e-375f79596196.png">

**Comment by sshumihin** [comment]
Of course, my first scene is opened and it include to build settings.
![2017-03-01_105840](https://cloud.githubusercontent.com/assets/7456778/23450952/bfe94f52-fe6e-11e6-8567-ea9f58163208.gif)

UPDATE: I figure it out. Unity editor is not case-sensitive for asset names. (unix-style?).

In addition, I think you shouldn't check an opened scene. For example, I'm going to add the DTD listener to main scene. You way is not comfortable for me.

And one more question: why don't you upload an source code for the plugin?

Thanks.
