### ISSUE TITLE
Неудачная компиляция (2.9.1 в Xcode, 2.9.2 в Unity)

### ISSUE THREAD

**Issue by mvasiliy7** [devtodev-analytics/unity-sdk#10]
Всем привет!

Пару недель назад интегрировал плагин DTD 2.9.1 и построил через него всю аналитику. Решил скомпилировать под iOS. Компиляция Xcode-проекта в Unity прошла нормально. Далее перенёс его на Mac, запустил в Xcode и тут началось - на устройстве игра запускается нормально, а вот когда делаю archive для загрузки в App Store - выбивает ошибку:
![2018-09-11_180800](https://user-images.githubusercontent.com/18324918/45364961-df6e5e00-b5f4-11e8-8f99-ebb558047d13.png)

Решил обновить плагин до 2.9.2 и попробовать снова. Удалил все файлы от старой версии, импортировал новую, прописал все ключи. Теперь при запуске игры, в консоли выпадает такая ошибка:
![2018-09-11_182639](https://user-images.githubusercontent.com/18324918/45365052-1b092800-b5f5-11e8-87a9-92be4812f4a4.png)

А при попытке компиляции Xcode-проекта в Unity вообще выпадает ворох ошибок и компиляция прерывается:
![2018-09-11_182658](https://user-images.githubusercontent.com/18324918/45365088-2e1bf800-b5f5-11e8-9ad0-22ba0fbd4a00.png)
![2018-09-11_182718](https://user-images.githubusercontent.com/18324918/45365089-2e1bf800-b5f5-11e8-9c54-b48e96b67eda.png)
![2018-09-11_182724](https://user-images.githubusercontent.com/18324918/45365090-2eb48e80-b5f5-11e8-8abc-ef015fc1ecb6.png)
![2018-09-11_182731](https://user-images.githubusercontent.com/18324918/45365091-2eb48e80-b5f5-11e8-8329-145fdeac2118.png)

При удалении версии 2.9.2 и возврата к 2.9.1 - игра снова запускается и компилируется в Unity без ошибок.

Данные о системе:
Xcode 9.4.1, Unity 2017.1.4p2, Windows 8.1, macOS High Sierra 10.13.6

Что не так с последней версией и что мне делать с этим? Заранее спасибо за помощь.

**Comment by Skazochnij** [comment]
Добрый день, попробуйте пожалуйста версию [2.9.3](https://github.com/devtodev-analytics/unity-sdk/releases/tag/v2.9.3) и сообщите повторяется ли ваша проблема

**Comment by mvasiliy7** [comment]
> Добрый день, попробуйте пожалуйста версию [2.9.3](https://github.com/devtodev-analytics/unity-sdk/releases/tag/v2.9.3) и сообщите повторяется ли ваша проблема

Добрый вечер! Ошибки при запуске игры и при компиляции в Unity (как в версии 2.9.2) теперь нет. Но ошибка при создании архива в xcode (как было в 2.9.1) осталась. Правда там уже немного другие версии файлов, скриншот прикладываю.
![2018-09-18_215229](https://user-images.githubusercontent.com/18324918/45703448-cc780280-bb8d-11e8-8fb1-6f4121935074.png)

**Comment by Skazochnij** [comment]
Какую версию XCode вы используете?

**Comment by Skazochnij** [comment]
Вероятно виноваты различные версии Xcode, попробуйте пожалуйста сархивировать в версии 10.0

**Comment by mvasiliy7** [comment]
> Вероятно виноваты различные версии Xcode, попробуйте пожалуйста сархивировать в версии 10.0

Доброе утро! XCode пока не получилось обновить. Проблему пока решил просто отключением bitcode в XCode. Без него всё нормально. Так что  можно топик закрывать.
