### ISSUE TITLE
Version=2.12.8.0, params: DevToDev.Analytics.OpenUdid and DevToDev.Analytics.Odin1

### ISSUE THREAD

**Issue by YuliyF** [devtodev-analytics/unity-sdk#13]
Can't find :
DevToDev.Analytics.OpenUdid
DevToDev.Analytics.Odin1

from doc: https://www.devtodev.com/help/75/the_secondary_methods_of_devtodev_sdk_for_unity/

**Comment by YuliyF** [comment]
![devtodev](https://user-images.githubusercontent.com/1027156/77089440-7f891c80-6a0e-11ea-9616-f1e2e5dfe792.jpg)

**Comment by RinatTalibullin** [comment]
Hello!

You can use DevToDev.Analytics.DeviceId for device identification. Documentation was updated.
