### ISSUE TITLE
[iOS] Error: An abnormal situation has occurred: the PlayerLoop internal function has been called recursively

### ISSUE THREAD

**Issue by maniaks1** [devtodev-analytics/unity-sdk#15]
Hello!

I get the following error when starting the application for some iOS clients:
"An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it."

Stacktrace:
DevToDev.Core.Utils.Helpers.DeviceHelperPlatform: GetUserAgentSring ()
DevToDev.Data.Metrics.Simple.UserInfoEvent: .ctor ()
DevToDev.Logic.User: AddSelfInfo ()
DevToDev.Logic.User: OnInitialized (Boolean)
DevToDev.Logic.SDKClient: OnServerConfigReceived (Response, Object)
DevToDev.Core.Network. <WaitForRequest> d__16: MoveNext ()
UnityEngine.SetupCoroutine: InvokeMoveNext (IEnumerator, IntPtr)

Last logs before the error:
"[D 01: 53: 06.155 0: 00: 03.324] [DevToDev] 2020/04/01 01:53:06: Metric Session Start Event added to storage",
"[D 01: 53: 06.158 0: 00: 03.327] [DevToDev] 2020/04/01 01:53:06: Metric Application Info added to storage",
"[E 01: 53: 06.757 0: 00: 03.926] An abnormal situation has occurred: the PlayerLoop internal function has been called recursively. Please contact Customer Support with a sample project so that we can reproduce the problem and troubleshoot it."

This error shows up on any versions of iOS and devices, but not always (according to information from the logs: 0-27 cases of the error at application startup). I can’t generate it locally.

DevToDev: 2.12.8
Unity: 2018.4.15

**Comment by RinatTalibullin** [comment]
Hello!
Thank you for your feedback. This issue will be fixed in the next update.

**Comment by RinatTalibullin** [comment]
Update 2.12.9 available with the fix.

**Comment by tomicagvg** [comment]
Hello!

I get the following error when starting the application zynga poker i am offline
