### ISSUE TITLE
AndroidManifest: minSdkVersion="10" broke a build

### ISSUE THREAD

**Issue by sshumihin** [devtodev-analytics/unity-sdk#2]
Hi!

You should remove this line from your manifest by path "Assets/Plugins/Android/AndroidManifest.xml".
It's broke my Android build.
In addition, a push service (Firebase) requires Android SDK 4.0 (API 14). This line is unnecessary.

Thanks.

**Comment by Skazochnij** [comment]
Hello!
Maybe you use extra plugins with higher minSdkVersion. Could you please describe in more details the error from Unity. Thanks.

**Comment by sshumihin** [comment]
There is a log error with a line <uses-sdk android:minSdkVersion="10"/>:

`CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_111\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Android_SDK\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\animated-vector-drawable-23.4.0\AndroidManifest.xml:3] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='11'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\customtabs-23.4.0\AndroidManifest.xml:3] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='15'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\facebook-android-sdk-4.17.0\AndroidManifest.xml:3] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='15'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\facebook-android-wrapper-7.9.0\AndroidManifest.xml:3] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='15'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-auth-10.2.0\AndroidManifest.xml:2] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-auth-base-10.2.0\AndroidManifest.xml:3] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-base-10.2.0\AndroidManifest.xml:2] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-basement-10.2.0\AndroidManifest.xml:2] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-drive-10.2.0\AndroidManifest.xml:2] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-games-10.2.0\AndroidManifest.xml:2] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-nearby-10.2.0\AndroidManifest.xml:2] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
Error: [Temp\StagingArea\AndroidManifest-main.xml:2, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-tasks-10.2.0\AndroidManifest.xml:2] Main manifest has <uses-sdk android:minSdkVersion='10'> but library uses minSdkVersion='14'
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, F:\Work\MyProject\Temp\StagingArea\android-libraries\MainLibProj\AndroidManifest.xml:13] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
[Temp\StagingArea\AndroidManifest-main.xml, F:\Work\MyProject\Temp\StagingArea\android-libraries\play-services-basement-10.2.0\AndroidManifest.xml:5] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.HostView:OnGUI()
`

GooglePlayService and Facebook add any needed info to the manifest automaticly.

**Comment by Skazochnij** [comment]
We remove this line in [v2.4](https://github.com/devtodev-analytics/unity-sdk/releases/tag/v2.4)
