### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by alehkudrevich** [devtodev-analytics/unity-sdk#4]
Hello, iOS build on iPhone crash when I try to initialize you service.
Unity 5.5.2f, DevToDev 2.4.3.

![2017-05-22 18 29 51](https://cloud.githubusercontent.com/assets/12971257/26316446/fc0f76de-3f1c-11e7-8071-fc4bb52ddf28.png)

**Comment by Skazochnij** [comment]
Hello! What do you use as a "Scripting Backend" and "Api Compatibility level" in Player Settings?

**Comment by alehkudrevich** [comment]
Scripting Backend: Mono 2x
Api Compatibility level: .NET 2.0

**Comment by Skazochnij** [comment]
Please try to use IL2CPP as Scripting Backend

**Comment by alehkudrevich** [comment]
I can't build project for IL2CPP. Is it necessary for this plugin?

**Comment by Skazochnij** [comment]
At this moment we do not support Mono 2x, but in future releases we will try to include its support.

**Comment by Skazochnij** [comment]
Please try v2.5.3 for Mono on iOS
