### ISSUE TITLE
Conflict with Google Play Game Services plugin

### ISSUE THREAD

**Issue by sshumihin** [devtodev-analytics/unity-sdk#6]
Hi!

It's might be no an issue but can you check it?

I have a conflict with 

```
<meta-data android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
```

There is my message on GPGS repo [https://github.com/playgameservices/play-games-plugin-for-unity/issues/2019#issuecomment-348481148](url)

**Comment by Skazochnij** [comment]
Hello, we working for update with included gps resolver in our plugin. Unfortunately, your link got 404 error :(

**Comment by sshumihin** [comment]
Sorry. Fixed link.
[GPGS conflict](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2019#issuecomment-348481148)

**Comment by Skazochnij** [comment]
Now we working on update with included GPS resolver. I think it's fix your issue. We try to release it as soon as possible

**Comment by Skazochnij** [comment]
Please try the last 2.7 version
