### ISSUE TITLE
can't import asset to project - console error

### ISSUE THREAD

**Issue by boris-741** [devtodev-analytics/unity-sdk#7]
after impoirting assetbundle to empty projet I have the following errors in unity console:

> Assets/devtodev/Window/DTDEditorViewModel.cs(23,76): error CS0246: The type or namespace name `PushMessage' could not be found. Are you missing an assembly reference?

> Assets/devtodev/Window/DevToDevSDK.cs(29,17): error CS0103: The name `Analytics' does not exist in the current context

>Assets/devtodev/Window/DevToDevSDK.cs(49,17): error CS0103: The name `PushManager' does not exist in the current context

>Assets/devtodev/Window/DevToDevSDK.cs(61,17): error CS0103: The name `Analytics' does not exist in the current context

I have Unity version 5.5. How can I integrate your package?

**Comment by Skazochnij** [comment]
Hello, Boris
Pleaase check that file devtodev_cross.dll located at Assets/Plugins/Standalone has the following platforms selected:

<img width="520" alt="standalone" src="https://user-images.githubusercontent.com/3314943/41602923-8a0a09de-73e4-11e8-94cd-9493c75429b8.png">

**Comment by boris-741** [comment]
Thank you for such a quick response. 
I did as you asked. But now I have the following errors:

> error CS1704: An assembly with the same name `UnityEngine.UI' has already been imported. Consider removing one of the references or sign the assembly
C:/Program Files/Unity 5.5.6f1/Editor/Data/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll (Location of the symbol related to previous error)
C:/Program Files/Unity 5.5.6f1/Editor/Data/UnityExtensions/Unity/GUISystem/Standalone/UnityEngine.UI.dll (Location of the symbol related to previous error)
error CS1704: An assembly with the same name `UnityEngine.Networking' has already been imported. Consider removing one of the references or sign the assembly
C:/Program Files/Unity 5.5.6f1/Editor/Data/UnityExtensions/Unity/Networking/UnityEngine.Networking.dll (Location of the symbol related to previous error)
C:/Program Files/Unity 5.5.6f1/Editor/Data/UnityExtensions/Unity/Networking/Standalone/UnityEngine.Networking.dll (Location of the symbol related to previous error)
error CS1704: An assembly with the same name `UnityEngine.HoloLens' has already been imported. Consider removing one of the references or sign the assembly
C:/Program Files/Unity 5.5.6f1/Editor/Data/UnityExtensions/Unity/UnityHoloLens/Runtime/UnityEngine.HoloLens.dll (Location of the symbol related to previous error)
C:/Program Files/Unity 5.5.6f1/Editor/Data/UnityExtensions/Unity/UnityHoloLens/RuntimeEditor/UnityEngine.HoloLens.dll (Location of the symbol related to previous error)

**Comment by boris-741** [comment]
Reimport All fix this issue. Thanks again

**Comment by Skazochnij** [comment]
You are welcome :)

**Comment by Anton-Notna** [comment]
Hello, I have the similar issure. devtodev_cross.dll looks like in your screenshot. "Reimport All" dont fix errors. 
Errors:
`Assets\devtodev\Window\DevToDevSDK.cs(30,17): error CS0234: The type or namespace name 'SetActiveLog' does not exist in the namespace 'Analytics' (are you missing an assembly reference?)`

`Assets\devtodev\Window\DevToDevSDK.cs(61,17): error CS0234: The type or namespace name 'Initialize' does not exist in the namespace 'Analytics' (are you missing an assembly reference?)`
